platform :ios,'8.0'
project 'MyBasketBall.xcodeproj'
target 'MyBasketBall' do
    pod 'HMSegmentedControl', '~> 1.5.2'    
    pod 'SDWebImage', '~> 3.7.5'
    pod 'MJRefresh'
    pod 'NJKWebViewProgress'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'YCXMenu'
    pod 'LKDBHelper'
    pod 'FMDB'
    pod 'YYText'
    pod 'YYModel'
    pod 'YYWebImage'
    pod 'YYImage'
   #pod 'ReactiveCocoa', '~> 5.0.0-alpha.3'
 use_frameworks!
    
end
